#Change the values please :)
SCREEN_WIDTH = 448
SCREEN_HEIGHT = 550
CAPTION = "Pacman"

#Pacman position
PACMAN_INITIAL_X = 210
PACMAN_INITIAL_Y = 268

#Pacman tiles
PACMAN_RIGHT_TILE_Y = 0
PACMAN_LEFT_TILE_Y = 16
PACMAN_UP_TILE_Y = 32
PACMAN_DOWN_TILE_Y = 48

#Ghost tiles
BLINKY_Y_TILE = 0
INKY_Y_TILE = 16
PINKY_Y_TILE = 32
CLYDE_Y_TILE = 48

#Fruit tiles
FRUIT_X_POS = 210
FRUIT_Y_POS = 268

#Pellets tiles
PELLET_Y_TILE = 192

#Sprite size
SPRITE_SIZE = 12


MAZE_1 = []